export const reducerCases: any = {
    SET_USER_INFO: 'SET_NEW_USER',
    IS_NEW_USER: 'IS_NEW_USER',
    SET_CONTACTS_MENU: "SET_CONTACTS_MENU",
    SET_SETTINGS_MENU : "SET_SETTINGS_MENU",
    SET_CURRENT_CHAT_USER: "SET_CURRENT_CHAT_USER",
    SET_MESSAGES: "SET_MESSAGES",
    SET_SOCKET: "SET_SOCKET",
    ADD_MESSAGE: "ADD_MESSAGE",
    SET_VOICE_CALL: "SET_VOICE_CALL",
    SET_VIDEO_CALL: "SET_VIDEO_CALL",
    END_CALL: "END_CALL",
    SET_INCOMING_VOICE_CALL: "SET_INCOMING_VOICE_CALL",
    SET_INCOMING_VIDEO_CALL: "SET_INCOMING_VIDEO_CALL",
    SET_ONLINE_USERS : "SET_ONLINE_USERS"
}